a = int(1)   	
b = int(2.8)	 
c = int("3") 	
x = float(1)     
y = float(2.8)   
z = float("3")   
w = float("4.2") 
j = str("s1") 	 
k = str(2)    	 
l = str(3.0)  
print(type(a))
print(type(x))
print(type(j))
print(type("a,b,c"))
	 
